version: '2'
services:
    library-cassandra:
        container_name: library-cassandra
        image: cassandra:2.2.7
        # volumes:
        #     - ~/volumes/jhipster/Library/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    library-cassandra-node:
        image: cassandra:2.2.7
        links:
            - library-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    library-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: library-cassandra-migration
        links:
            - library-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
